t=tuple()
print(t)
#conversion list to tuple
t1=tuple([23,12,2,3,14])
print(t1)

hero1=("batman","bruce wyne")
hero2=("wonder woman","diana prince")
new_tuple=(hero1,hero2)
print(new_tuple)
print(new_tuple[0])
print(new_tuple[0][0])
print(new_tuple[0][1])
print(new_tuple[1][0])
print(new_tuple[1][1])